In [1]:
import torch
import torch.nn as nn

import nltk

import random
import numpy as np

In [2]:
nltk.download('gutenberg')

[nltk_data] Downloading package gutenberg to
[nltk_data]     /Users/cillian/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


True

In [6]:
nltk.corpus.gutenberg.fileids()
# raw = nltk.corpus.gutenberg.raw('shakespeare-hamlet.txt')

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

In [7]:
raw = nltk.corpus.gutenberg.raw('shakespeare-hamlet.txt')

In [8]:
raw[:500]

"[The Tragedie of Hamlet by William Shakespeare 1599]\n\n\nActus Primus. Scoena Prima.\n\nEnter Barnardo and Francisco two Centinels.\n\n  Barnardo. Who's there?\n  Fran. Nay answer me: Stand & vnfold\nyour selfe\n\n   Bar. Long liue the King\n\n   Fran. Barnardo?\n  Bar. He\n\n   Fran. You come most carefully vpon your houre\n\n   Bar. 'Tis now strook twelue, get thee to bed Francisco\n\n   Fran. For this releefe much thankes: 'Tis bitter cold,\nAnd I am sicke at heart\n\n   Barn. Haue you had quiet Guard?\n  Fran. Not"

# Char to Dic

In [9]:
char2index = {}
index2char = []

In [10]:
for char in raw:
    if char not in char2index.keys():
        char2index[char] = len(char2index)
        index2char.append(char)

In [12]:
char2index

{'[': 0,
 'T': 1,
 'h': 2,
 'e': 3,
 ' ': 4,
 'r': 5,
 'a': 6,
 'g': 7,
 'd': 8,
 'i': 9,
 'o': 10,
 'f': 11,
 'H': 12,
 'm': 13,
 'l': 14,
 't': 15,
 'b': 16,
 'y': 17,
 'W': 18,
 'S': 19,
 'k': 20,
 's': 21,
 'p': 22,
 '1': 23,
 '5': 24,
 '9': 25,
 ']': 26,
 '\n': 27,
 'A': 28,
 'c': 29,
 'u': 30,
 'P': 31,
 '.': 32,
 'n': 33,
 'E': 34,
 'B': 35,
 'F': 36,
 'w': 37,
 'C': 38,
 "'": 39,
 '?': 40,
 'N': 41,
 ':': 42,
 '&': 43,
 'v': 44,
 'L': 45,
 'K': 46,
 'Y': 47,
 ',': 48,
 'I': 49,
 'q': 50,
 'G': 51,
 'M': 52,
 'R': 53,
 '-': 54,
 'D': 55,
 'O': 56,
 'x': 57,
 ';': 58,
 'Q': 59,
 'z': 60,
 '(': 61,
 ')': 62,
 'V': 63,
 '!': 64,
 'j': 65,
 'Z': 66}

In [13]:
index2char

['[',
 'T',
 'h',
 'e',
 ' ',
 'r',
 'a',
 'g',
 'd',
 'i',
 'o',
 'f',
 'H',
 'm',
 'l',
 't',
 'b',
 'y',
 'W',
 'S',
 'k',
 's',
 'p',
 '1',
 '5',
 '9',
 ']',
 '\n',
 'A',
 'c',
 'u',
 'P',
 '.',
 'n',
 'E',
 'B',
 'F',
 'w',
 'C',
 "'",
 '?',
 'N',
 ':',
 '&',
 'v',
 'L',
 'K',
 'Y',
 ',',
 'I',
 'q',
 'G',
 'M',
 'R',
 '-',
 'D',
 'O',
 'x',
 ';',
 'Q',
 'z',
 '(',
 ')',
 'V',
 '!',
 'j',
 'Z']

In [14]:
dim = len(char2index)
print("Dimension of input . & output : ", dim)


Dimension of input . & output :  67


In [15]:
char2vec = {}
eye = np.eye(len(char2index))

In [16]:
eye

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [17]:
for item in char2index.keys():
    char2vec[item] = eye[char2index[item], :]

In [18]:
char2vec

{'[': array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'T': array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'h': array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'e': array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [19]:
char2vec['a']

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
data = np.array([char2vec[char] for char in raw])

In [21]:
data

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Define Model

In [22]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers):
        super(RNN, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.num_layers = num_layers
        
        self.rnn = nn.RNN(input_size, hidden_size, num_layers)
        self.fc = nn.Linear(hidden_size, output_size)
        
    def forward(self, input, hidden):
        out, hidden = self.rnn(input, hidden)
        fc_out = self.fc(out)
        return fc_out, hidden
    
    def init_hidden(self):
        hidden = torch.zeros(self.num_layers, 1, self.hidden_size) # if cuda -> hidden = torch.zeros(self.num_layers, 1, self.hidden_size).cuda() 
        return hidden

In [23]:
model = RNN(dim, 500, dim, 1)
# if cuda -> model = RNN(dim, 500, dim, 1).cuda()

In [24]:
model

RNN(
  (rnn): RNN(67, 500)
  (fc): Linear(in_features=500, out_features=67, bias=True)
)

# Train Model

In [25]:
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)
loss = nn.CrossEntropyLoss()

In [26]:
seq_len = 100
num_epochs = 5

In [28]:
for epoch in range(num_epochs):
    sp = list(range(0, len(data) - 2 * seq_len, seq_len))
    sp = np.add(sp, random.randint(0, seq_len))
    random.shuffle(sp)
    
    for i in range(len(sp)):
        hidden = model.init_hidden()
        cost = 0
        for pos in range(sp[i], sp[i] + seq_len):
            X = torch.from_numpy(data[pos]).type(torch.FloatTensor).reshape(1, 1, dim)
            # if cuda -> X = torch.from_numpy(data[pos]).type(torch.FloatTensor).cuda().reshape(1, 1, dim)
            Y = torch.from_numpy(data[pos+1])
            # if cuda -> Y = torch.from_numpy(data[pos+1]).cuda()
            
            _, y = Y.max(dim=0)
            
            pre, hidden = model(X, hidden)
            cost += loss(pre.reshape(1, dim), y.reshape(1))
            # if cuda -> cost += loss(pre.reshape(1, dim), y.reshape(1).cuda())
            
        optimizer.zero_grad()
        cost.backward()
        
        nn.utils.clip_grad_norm_(model.parameters(), 5)
        optimizer.step()
        
        if (i + 1) % 100 == 0:
            print('Epoch [%d/%d], Iter [%d/%d] Loss: %.4f'
                     %(epoch+1, num_epochs, i + 1, len(sp), cost.item()))

Epoch [1/5], Iter [100/1627] Loss: 318.0188
Epoch [1/5], Iter [200/1627] Loss: 331.1754
Epoch [1/5], Iter [300/1627] Loss: 292.7415
Epoch [1/5], Iter [400/1627] Loss: 247.4618
Epoch [1/5], Iter [500/1627] Loss: 243.3322
Epoch [1/5], Iter [600/1627] Loss: 229.5817
Epoch [1/5], Iter [700/1627] Loss: 246.2391
Epoch [1/5], Iter [800/1627] Loss: 274.4293
Epoch [1/5], Iter [900/1627] Loss: 204.3063
Epoch [1/5], Iter [1000/1627] Loss: 221.8965
Epoch [1/5], Iter [1100/1627] Loss: 243.1794
Epoch [1/5], Iter [1200/1627] Loss: 223.7001
Epoch [1/5], Iter [1300/1627] Loss: 225.8744
Epoch [1/5], Iter [1400/1627] Loss: 226.1897
Epoch [1/5], Iter [1500/1627] Loss: 262.2567
Epoch [1/5], Iter [1600/1627] Loss: 220.5584
Epoch [2/5], Iter [100/1627] Loss: 221.0530
Epoch [2/5], Iter [200/1627] Loss: 258.0485
Epoch [2/5], Iter [300/1627] Loss: 221.2137
Epoch [2/5], Iter [400/1627] Loss: 189.5426
Epoch [2/5], Iter [500/1627] Loss: 207.3602
Epoch [2/5], Iter [600/1627] Loss: 210.6047
Epoch [2/5], Iter [700/16

# Test Model

In [31]:
start_num = 5
text = index2char[start_num]

model.eval()
hidden = model.init_hidden()

X_test = torch.from_numpy(data[start_num]).type(torch.FloatTensor).reshape(1, 1, dim)
# cuda -> X_test = torch.from_numpy(data[start_num]).type(torch.FloatTensor).cuda().reshape(1, 1, dim)

for i in range(500):
    pre, hidden = model(X_test, hidden)
    temp = pre.reshape(-1).cpu().data.numpy()
    best_5 = np.argsort(temp)[::-1][:5]
    temp = np.exp(temp[best_5])
    temp = temp / temp.sum()
    pre = np.random.choice(best_5, 1, p=temp)[0]
    curr_char = index2char[pre]
    text += curr_char
    X_test = torch.from_numpy(char2vec[curr_char]).type(torch.FloatTensor).reshape(1, 1, dim)
    # cuda -> X_test = torch.from_numpy(char2vec[curr_char]).type(torch.FloatTensor).cuda().reshape(1, 1, dim)
    
print("* Generated Text: \n\n", text)

* Generated Text: 

 rring you this fray?

 Pol. Thy way you. Boon will sore you montinge, and word would

   Hor. Marrest he sent he hare your Lord, as I haue fineres

   Oan. Chare your soott, ond,
A all with is this foule your Myose. I would you and an in are withins shist things shast a there it you may you his word hes mort that the pursititir,
And hath you the heere titerall he as the Kisg. It a Praise yiur all at that thought that I haue feare,
A would you mine it sinet thinge in toud are wat his a assant yeue
