In [137]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable
import torch.nn.functional as F



import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
%matplotlib inline

In [129]:
iris = datasets.load_iris()

iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [130]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [131]:
train_x, test_x, train_y, test_y = train_test_split(iris.data, iris.target, test_size=0.3)

In [132]:
train_x.shape, train_y.shape

((105, 4), (105,))

In [133]:
x, y = torch.from_numpy(train_x).float(), torch.from_numpy(train_y).long()
x.shape, y.shape

(torch.Size([105, 4]), torch.Size([105]))

In [138]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4, 10)
        self.fc2 = nn.Linear(10, 3)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        
        return x
        

In [139]:
model = Net()
loss = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [140]:
for step in range(500):
    X = Variable(torch.Tensor(train_x).float())
    Y = Variable(torch.Tensor(train_y).long())
    pre = model(X)
    cost = loss(pre, Y)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if step % 50 == 0:
        print('Step: ', step, ", Cost: ", cost.item())

Step:  0 , Cost:  1.1785575151443481
Step:  50 , Cost:  0.47270944714546204
Step:  100 , Cost:  0.17916364967823029
Step:  150 , Cost:  0.09748333692550659
Step:  200 , Cost:  0.07757479697465897
Step:  250 , Cost:  0.06875041127204895
Step:  300 , Cost:  0.06357739865779877
Step:  350 , Cost:  0.06006120145320892
Step:  400 , Cost:  0.057437796145677567
Step:  450 , Cost:  0.055361125618219376


In [141]:
test_data = torch.from_numpy(test_x).float()
test_label = torch.from_numpy(test_y).long()

In [144]:
test_X = Variable(torch.Tensor(test_x).float())
test_Y = Variable(torch.Tensor(test_y).long())

output = model(test_X)

In [146]:
_, predicted = torch.max(output.data, 1)

In [147]:
predicted

tensor([0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2, 0, 0, 1, 2, 2, 1, 1, 2, 0,
        1, 1, 2, 0, 2, 2, 0, 2, 0, 0, 1, 2, 1, 0, 2, 0, 2, 1, 1, 1, 1])

In [148]:
test_Y

tensor([0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2, 0, 0, 1, 1, 2, 1, 1, 2, 0,
        1, 1, 2, 0, 2, 2, 0, 2, 0, 0, 1, 2, 1, 0, 2, 0, 2, 1, 1, 1, 1])

In [149]:
print('Accuracy: %d %%' % (100 * torch.sum(predicted == test_Y) / len(test_Y)))

Accuracy: 97 %
